// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NewsAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607155007_AgregarSistemaAutomatizado")]
    partial class AgregarSistemaAutomatizado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("Audio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Email")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("diaria");

                    b.Property<string>("GradoDesarrolloResumen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hashtags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lenguaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximaEjecucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaEjecucion")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("Frecuencia");

                    b.HasIndex("ProximaEjecucion");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.ConfiguracionUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UrlConfiableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrlConfiableId");

                    b.HasIndex("ConfiguracionId", "UrlConfiableId")
                        .IsUnique();

                    b.ToTable("ConfiguracionUrls");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Configuracion_Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Configuracion_usuarios");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.EjecucionProgramada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EmailEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajeError")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NoticiasEncontradas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoticiasProcessadas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResumenGeneradoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaEjecucion");

                    b.HasIndex("ResumenGeneradoId");

                    b.HasIndex("ConfiguracionId", "Estado");

                    b.ToTable("EjecucionesProgramadas");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.NoticiaExtraida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Hashtags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Noticia");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.ResumenGenerado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfiguracionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContenidoResumen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoticiasProcesadas")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TiempoProcesamiento")
                        .HasColumnType("REAL");

                    b.Property<string>("UrlOrigen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Resumen");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.UrlConfiable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraccionesExitosas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraccionesFallidas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoFuente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("RSS");

                    b.Property<DateTime?>("UltimaExtraccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.HasIndex("UsuarioId", "Url")
                        .IsUnique();

                    b.ToTable("UrlsConfiables");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Configuracion", b =>
                {
                    b.HasOne("NewsAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAI.Dominio.Entidades.Usuario", null)
                        .WithMany("Configuraciones")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.ConfiguracionUrl", b =>
                {
                    b.HasOne("NewsAI.Dominio.Entidades.Configuracion", "Configuracion")
                        .WithMany("ConfiguracionUrls")
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAI.Dominio.Entidades.UrlConfiable", "UrlConfiable")
                        .WithMany("ConfiguracionUrls")
                        .HasForeignKey("UrlConfiableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuracion");

                    b.Navigation("UrlConfiable");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Configuracion_Usuario", b =>
                {
                    b.HasOne("NewsAI.Dominio.Entidades.Configuracion", "Configuracion")
                        .WithMany()
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuracion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.EjecucionProgramada", b =>
                {
                    b.HasOne("NewsAI.Dominio.Entidades.Configuracion", "Configuracion")
                        .WithMany()
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAI.Dominio.Entidades.ResumenGenerado", "ResumenGenerado")
                        .WithMany()
                        .HasForeignKey("ResumenGeneradoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Configuracion");

                    b.Navigation("ResumenGenerado");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.ResumenGenerado", b =>
                {
                    b.HasOne("NewsAI.Dominio.Entidades.Configuracion", "Configuracion")
                        .WithMany()
                        .HasForeignKey("ConfiguracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuracion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.UrlConfiable", b =>
                {
                    b.HasOne("NewsAI.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Configuracion", b =>
                {
                    b.Navigation("ConfiguracionUrls");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.UrlConfiable", b =>
                {
                    b.Navigation("ConfiguracionUrls");
                });

            modelBuilder.Entity("NewsAI.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Configuraciones");
                });
#pragma warning restore 612, 618
        }
    }
}
